### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by danieldeesousa** [makerdiary/nrf52840-mdk#1]
I was wondering if there was a BOM for the hardware for this project in case I wanted to base my hardware project off of this sometime in the future.

**Comment by caizelin** [comment]
@danieldeesousa Hi, you can check the [schematic](https://github.com/makerdiary/nrf52840-mdk/blob/master/docs/hardware/nrf52840-mdk-schematic_v1_0.pdf) for more hardware details and choose the right components for your own project.

**Comment by saulpw** [comment]
Seconded.  In particular wanting to know the external flash part number.  I am giving myself a headache trying to read it off the board and was hoping that it was mentioned somewhere.

**Comment by caizelin** [comment]
> Seconded. In particular wanting to know the external flash part number. I am giving myself a headache trying to read it off the board and was hoping that it was mentioned somewhere.

@saulpw The PN of external flash is MX25R6435F, the same as Nordic's nRF52840-DK. You can use the QSPI example from nRF5 SDK by adapting the pin number.

**Comment by caizelin** [comment]
Pls reopen this issue if you have any concerns. Thanks!

**Comment by g-e-r** [comment]
I’m interested in knowing the regulator parts.
