### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by danieldeesousa** [makerdiary/nrf52840-mdk#2]
Can I program this board over an interface which is not USB such as SWD?

If so, what would you recommend as a debugger?

**Comment by Lindenk** [comment]
It looks like there are pins for SWD/JTAG on the right of the board. I'm currently using [this programmer](https://www.adafruit.com/product/3571) and you probably will also need a break out board [like this](https://www.adafruit.com/product/2743).

**Comment by wez** [comment]
I hooked mine up to a jlink using the adafruit breakout board.  Pinout and some more info is captured here: https://github.com/nrf-rs/nrf52840-mdk-rs#jlink

**Comment by caizelin** [comment]
@danieldeesousa The SWD pins are on the right header of the board. The board has a [DAPLink](https://github.com/ARMmbed/DAPLink) debugger integrated. It should be more convenient. If you want to use an external debugger, J-Link is recommended.

**Comment by caizelin** [comment]
Pls reopen this issue if you have any concerns. Thanks!
