### ISSUE TITLE
What version of zephyr does do the examples expect?

### ISSUE THREAD

**Issue by Lindenk** [makerdiary/nrf52840-mdk#3]
Currently most of the zephyr board configuration does not work as the guide says. 

For example, the Kconfig.defconfig file does not have typing information required by zephyr and therefore fails to build. Attempting to assign 'y' to ARM_MPU_NRF52X fails in nrf52840_mdk_defconfig because ARM_MPU_NRF52X does not exist. There's also a slew of problems with the .dts file.

Please fix the documentation or config files so they work.

Steps to reproduce:
Attempt to follow the [zephyr guide](https://wiki.makerdiary.com/nrf52840-mdk/zephyr/#__comments)

**Comment by caizelin** [comment]
@Lindenk Thanks. I will fix this issue soon.

**Comment by caizelin** [comment]
@Lindenk 
The zephyr examples and docs are up to date now.
Also, the official zephyr repo has supported nrf52840-mdk board. You can just clone the lastest master from [zephyrproject-rtos/zephyr](https://github.com/zephyrproject-rtos/zephyr) to play.
Enjoy!

**Comment by caizelin** [comment]
Pls reopen this issue if you have any concerns. Thanks!
