### ISSUE TITLE
Antenna selection

### ISSUE THREAD

**Issue by der-tobi** [makerdiary/nrf52840-mdk#4]
According to the Datasheet we have a selectable U.FL Connector for an external Antenna on the nRF52840-MDK.
How can we select between the internal (Chip) an the external Antenna?
Do you have a code-example of the usage for the nRF-SDK 15.2?
I just need a BLE-Beacon every x ms over the external Antenna.

(https://community.makerdiary.com/t/u-fl-connector-selection/212)

**Comment by caizelin** [comment]
Hi there,
A rework must be performed before the U.FL connector can be used; this involves swapping the position of a 3.3nH chip inductor. The modified board would appear as follows.
* **Here is for the external antenna:**
![external-ant](https://user-images.githubusercontent.com/37929607/46988882-41a70b00-d12d-11e8-8eca-5ac00ad9d1b2.JPG)

* **And here is for the chip antenna:**
![chip-ant](https://user-images.githubusercontent.com/37929607/46988979-afebcd80-d12d-11e8-849e-3937ff33deaf.JPG)

nRF-SDK 15.2 support is working in process. I will update the examples later. 

Best,
Zelin

**Comment by der-tobi** [comment]
Oops, that kind of "selectable". 
Thank you for your answer.
Kind regards,
Tobi

**Comment by aeozyalcin** [comment]
@caizelin sorry to bring up an old thread, but can you confirm the 1 pF capacitor does not need to be moved? Looking at the schematic, the chip antenna uses L4 (3.3nH) and C38 (1pF) as a matching network for 50 ohm chip antenna. The instructions here only say to move L4 (3.3 nH). Can you confirm C38 (1pF) does **_not_** need to be moved the empty C46 footprint? I figured we would need to move both to match 50 ohm impedance. 

Thanks!

**Comment by cdeletre** [comment]
I've manage to make the external antenna working by only moving the L4. That wasn't a piece of cake with this size of component (0402) but I did it !
