### ISSUE TITLE
circuitPython doesn't work on this board

### ISSUE THREAD

**Issue by uyoyo117** [makerdiary/nrf52840-mdk#43]
i tried to flesh the hex file from adafruit site, and i get noting
also tried to bulid my own and flash and the board still doesn't work
all other example HEX fill works

**Comment by xiongyihui** [comment]
Just checked it. I got the same. The MCU ran into lockup. Will look into it.

**Comment by xiongyihui** [comment]
The issue is caused by a wrong softdevice or no softdevice. We should merge the circuitpython firmware with the softdevice at https://github.com/adafruit/circuitpython/tree/main/ports/nrf/bluetooth/s140_nrf52_6.1.0
