### ISSUE TITLE
Compiling external/freertos/portable/ARM/nrf52/port.c

### ISSUE THREAD

**Issue by 13291827129** [makerdiary/nrf52840-mdk#48]
../../../../nrf_sdks/nRF5_SDK_15.2.0_9412b96/external/freertos/portable/ARM/nrf52/port.c:52:7: error: expected '(' before 'void'
 __ASM void vPortSVCHandler( void )
       ^~~~
../../../../nrf_sdks/nRF5_SDK_15.2.0_9412b96/external/freertos/portable/ARM/nrf52/port.c:64:13: error: stray '#' in program
     mov r0, #0
             ^
../../../../nrf_sdks/nRF5_SDK_15.2.0_9412b96/external/freertos/portable/ARM/nrf52/port.c:87:13: error: stray '#' in program
     mov r0, #(configMAX_SYSCALL_INTERRUPT_PRIORITY << (8 - configPRIO_BITS))
             ^
../../../../nrf_sdks/nRF5_SDK_15.2.0_9412b96/external/freertos/portable/ARM/nrf52/port.c:112:14: error: stray '#' in program
     tst r14, #0x10
              ^
../../../../nrf_sdks/nRF5_SDK_15.2.0_9412b96/external/freertos/portable/ARM/nrf52/port.c:123:13: error: stray '#' in program
     mov r0, #(configMAX_SYSCALL_INTERRUPT_PRIORITY << (8 - configPRIO_BITS))
             ^

**Comment by caizelin** [comment]
@13291827129 Solved. Use `<sdk>external/freertos/portable/GCC/nrf52/port.c` instead if you are using GCC compiler.
