### ISSUE TITLE
External U.FL connector selector

### ISSUE THREAD

**Issue by SethSenpai** [makerdiary/nrf52840-mdk#5]
Hi there,

I was wondering how to select the external antenna connector on the board. I could not find anything in the documentation regarding this. I presume I need to re-solder a capacitor. If you so kindly could indicate which one I need to move that would be great!

Kind regards,
Seth

**Comment by SethSenpai** [comment]
Nevermind I just checked the closed issues and the explanation is in there.

**Comment by SethSenpai** [comment]
Perhaps it is prudent to provide this documentation on the website as well. Digging through closed github issues is not everyones cup of tea.

**Comment by caizelin** [comment]
> Perhaps it is prudent to provide this documentation on the website as well. Digging through closed github issues is not everyones cup of tea.

You are right. I will add this to the wiki.
